"""remove_notification_level_sent

Revision ID: c59d747ad0b1
Revises: 0004_add_line_to_incidents
Create Date: 2026-04-01 14:52:50.256740
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c59d747ad0b1'
down_revision: Union[str, Sequence[str], None] = '0004_add_line_to_incidents'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'notification_level_sent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('notification_level_sent', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
